#!/bin/sh

# Set up an icon tray
# trayer --edge top --align right --SetDockType true --SetPartialStrut true --expand true --width 10 --transparent true --tint 0x2B2E37 --height 18 &
redshift -l 40.0:-105.3 -t 5700:3600 -g 0.8 -m randr -v

# Set the default X cursor to the usual pointer
xsetroot -cursor_name left_ptr

# Set a nice background
feh --bg-fill --no-fehbg ~/.xmonad/wallpaper.jpg

# Power Management
xfce4-power-manager &

if [ -x /usr/bin/nm-applet ] ; then
   nm-applet --sm-disable &
fi
